keys:
  - &asahi_zazed age13nkmhuwt8zcfu8d73es8z04lxep6vh29efzk7z0fmwufdsymzcvsx5kxq6
  - &server_zazed age15766rhqx4547pmhh2u722skr4qdngmqap0g2sw629llt6sg9jaas527lmr
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *asahi_zazed
      - *server_zazed
