keys:
  - &asahi_zazed age13nkmhuwt8zcfu8d73es8z04lxep6vh29efzk7z0fmwufdsymzcvsx5kxq6
  - &server_zazed age1hr56vj6vf2kvreucw0k4t509tas36ed73ugjc4w6p90xtk7nxc9slm234q
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *asahi_zazed
      - *server_zazed
