# Auto-generated using compose2nix v0.3.2-pre.
{
  pkgs,
  lib,
  config,
  ...
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces =
    let
      matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
    in
    {
      "${matchAll}".allowedUDPPorts = [ 53 ];
    };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."tm-server" = {
    image = "lduriez/tmserver";
    environment = {
      "SERVER_ADM_PASSWORD" = "caralho";
      "SERVER_DESC" = "atrasados";
      "SERVER_NAME" = "atrasados mentais";
      "SERVER_SA_PASSWORD" = "caralho";
    };
    ports = [
      "2350:2350/tcp"
      "3450:3450/tcp"
      "8008:80/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=tmserver"
      "--network=tmnf_default"
    ];
  };
  systemd.services."podman-tm-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-tmnf_default.service"
    ];
    requires = [
      "podman-network-tmnf_default.service"
    ];
    partOf = [
      "podman-compose-tmnf-root.target"
    ];
    wantedBy = [
      "podman-compose-tmnf-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-tmnf_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f tmnf_default";
    };
    script = ''
      podman network inspect tmnf_default || podman network create tmnf_default
    '';
    partOf = [ "podman-compose-tmnf-root.target" ];
    wantedBy = [ "podman-compose-tmnf-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-tmnf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
