#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

FLAKE_SYSTEM="nixosConfigurations.simple-vm.config.system.build.vm"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting vm...${NC}"
nix --extra-experimental-features 'nix-command flakes' run .#$FLAKE_SYSTEM $@
