#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Define the variable for the external bar value
# Check if Übersicht is running
yabai -m config external_bar "all:0:0" \
	mouse_follows_focus off \
	focus_follows_mouse autoraise \
	window_zoom_persist off \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity on \
	window_opacity_duration 0.2 \
	active_window_opacity 1.0 \
	normal_window_opacity 0.95 \
	insert_feedback_color 0xff9dd274 \
	split_ratio 0.50 \
	auto_balance off \
	auto_padding on \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	top_padding 3 \
	bottom_padding 5 \
	left_padding 5 \
	right_padding 5 \
	window_gap 6

# Other configurations...
# Exclude problematic apps from being managed:
yabai -m rule --add app="^(iina|LuLu|Calculator|Software Update|Dictionary|UTM|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m space 1 --label web
yabai -m space 2 --label dev
yabai -m space 3 --label misc
yabai -m space 4 --label social
yabai -m space 5 --label music
yabai -m space 6 --label notes

yabai -m config layout bsp

# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'
