[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "None"

[font]

normal.family = "Iosevka Nerd Font"
bold.family = "Iosevka Nerd Font"
italic.family = "Iosevka Nerd Font"
bold_italic.family = "Iosevka Nerd Font"

size = 15.0
